<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Sales Report - {{ $summary['period'] }}</title>
    <style>
        @page {
            margin: 1cm;
        }

        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 10pt;
            color: #333;
            line-height: 1.4;
        }

        .header {
            border-bottom: 2px solid #4f46e5;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .header table {
            width: 100%;
        }

        .report-title {
            font-size: 20pt;
            font-weight: bold;
            color: #1e1b4b;
            margin: 0;
        }

        .company-info {
            text-align: right;
            font-size: 9pt;
            color: #666;
        }

        /* Summary Cards */
        .summary-container {
            margin-bottom: 30px;
            width: 100%;
        }

        .summary-card {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 15px;
            width: 22%;
            display: inline-block;
            vertical-align: top;
            margin-right: 1.5%;
            border-radius: 8px;
        }

        .summary-label {
            font-size: 8pt;
            color: #64748b;
            text-transform: uppercase;
            margin-bottom: 5px;
        }

        .summary-value {
            font-size: 14pt;
            font-weight: bold;
            color: #0f172a;
        }

        /* Table Styles */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th {
            background-color: #4f46e5;
            color: white;
            text-align: left;
            padding: 10px 5px;
            font-size: 8pt;
            text-transform: uppercase;
        }

        td {
            padding: 8px 5px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 9pt;
        }

        tr:nth-child(even) {
            background-color: #f1f5f9;
        }

        .text-right {
            text-align: right;
        }

        .amount {
            font-family: 'Courier', monospace;
            font-weight: bold;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            font-size: 8pt;
            text-align: center;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 5px;
        }

        .status-badge {
            font-size: 7pt;
            padding: 2px 5px;
            border-radius: 4px;
            background: #dcfce7;
            color: #166534;
            text-transform: uppercase;
        }
    </style>


</head>

<body>

    <div class="header">
        <table>
            <tr>
                <td>
                    <h1 class="report-title">Sales Report</h1>
                    <p style="margin: 5px 0 0 0; color: #64748b;">Period: {{ $summary['period'] }}</p>
                </td>
                <td class="company-info">
                    <strong>Generated By:</strong> {{ auth()->user()->name }}<br>
                    <strong>Date:</strong> {{ now()->format('M d, Y H:i') }}<br>
                    <strong>Tenant ID:</strong> #{{ auth()->user()->tenant_id }}
                </td>
            </tr>
        </table>
    </div>

    <div class="summary-container">
        <div class="summary-card">
            <div class="summary-label">Total Revenue</div>
            <div class="summary-value">GHS {{ number_format($summary['total_revenue'], 2) }}</div>
        </div>
        <div class="summary-card">
            <div class="summary-label">Units Sold</div>
            <div class="summary-value">{{ number_format($summary['total_units']) }}</div>
        </div>
        <div class="summary-card">
            <div class="summary-label">Total Discounts</div>
            <div class="summary-value">GHS {{ number_format($summary['total_discount'], 2) }}</div>
        </div>
        <div class="summary-card" style="margin-right: 0;">
            <div class="summary-label">Net Sales</div>
            <div class="summary-value">GHS
                {{ number_format($summary['total_revenue'] - $summary['total_discount'], 2) }}
            </div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Invoice</th>
                <th>Product</th>
                <th>Variation</th>
                <th class="text-right">Qty</th>
                <th class="text-right">Unit Price</th>
                <th class="text-right">Total</th>
                <th>Customer</th>
                <th>Method</th>
            </tr>
        </thead>
        <tbody>
            @foreach($sales as $sale)
                <tr>
                    <td>{{ $sale->sale_date->format('d/m/y') }}</td>
                    <td><small>#{{ $sale->invoice_number ?? $sale->id }}</small></td>
                    <td><strong>{{ $sale->product->name }}</strong></td>
                    <td>{{ $sale->variation?->type ?? 'N/A' }}</td>
                    <td class="text-right">{{ $sale->quantity }}</td>
                    <td class="text-right amount">{{ number_format($sale->unit_price, 2) }}</td>
                    <td class="text-right amount">{{ number_format($sale->total_amount, 2) }}</td>
                    <td>{{ $sale->customer?->name ?? 'Walk-in' }}</td>
                    <td><span class="status-badge">{{ $sale->payment_method }}</span></td>
                </tr>
            @endforeach
        </tbody>
    </table>