<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Stock Balance Report - {{ now()->format('M d, Y') }}</title>
    <style>
        @page {
            margin: 1cm;
        }

        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 10pt;
            color: #333;
            line-height: 1.4;
        }

        .header {
            border-bottom: 2px solid #0f172a;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }

        .header table {
            width: 100%;
        }

        .report-title {
            font-size: 20pt;
            font-weight: bold;
            color: #0f172a;
            margin: 0;
        }

        .company-info {
            text-align: right;
            font-size: 9pt;
            color: #666;
        }

        /* Summary Cards */
        .summary-container {
            margin-bottom: 30px;
            width: 100%;
        }

        .summary-card {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            padding: 15px;
            width: 30%;
            display: inline-block;
            vertical-align: top;
            margin-right: 2%;
            border-radius: 8px;
        }

        .summary-label {
            font-size: 8pt;
            color: #64748b;
            text-transform: uppercase;
            margin-bottom: 5px;
        }

        .summary-value {
            font-size: 14pt;
            font-weight: bold;
            color: #0f172a;
        }

        /* Table Styles */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th {
            background-color: #0f172a;
            color: white;
            text-align: left;
            padding: 10px 5px;
            font-size: 8pt;
            text-transform: uppercase;
        }

        td {
            padding: 8px 5px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 9pt;
        }

        tr:nth-child(even) {
            background-color: #f8fafc;
        }

        .text-right {
            text-align: right;
        }

        .amount {
            font-family: 'Courier', monospace;
            font-weight: bold;
        }

        /* Status Badges */
        .badge {
            font-size: 7pt;
            padding: 2px 6px;
            border-radius: 4px;
            text-transform: uppercase;
            font-weight: bold;
        }

        .badge-success {
            background: #dcfce7;
            color: #166534;
        }

        .badge-warning {
            background: #fef9c3;
            color: #854d0e;
        }

        .badge-danger {
            background: #fee2e2;
            color: #991b1b;
        }

        .variation-text {
            font-size: 8pt;
            color: #64748b;
            font-style: italic;
            display: block;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            font-size: 8pt;
            text-align: center;
            color: #94a3b8;
            border-top: 1px solid #e2e8f0;
            padding-top: 5px;
        }
    </style>


</head>

<body>

    <div class="header">
        <table>
            <tr>
                <td>
                    <h1 class="report-title">Stock Balance</h1>
                    <p style="margin: 5px 0 0 0; color: #64748b;">Inventory Audit: {{ now()->format('F d, Y') }}</p>
                </td>
                <td class="company-info">
                    <strong>Generated By:</strong> {{ auth()->user()->name }}<br>
                    <strong>Tenant:</strong> {{ auth()->user()->tenant->name ?? 'Default' }}<br>
                    <strong>Items:</strong> {{ count($products) }}
                </td>
            </tr>
        </table>
    </div>

    @php
        $totalValuation = $products->sum(fn($p) => $p->quantity * ($p->unit_price ?? 0));
        $lowStockCount = $products->filter(fn($p) => $p->quantity <= ($p->min_stock_threshold ?? 10))->count();
    @endphp

    <div class="summary-container">
        <div class="summary-card">
            <div class="summary-label">Inventory Value (Cost)</div>
            <div class="summary-value">GHS {{ number_format($totalValuation, 2) }}</div>
        </div>
        <div class="summary-card" style="margin-right: 0;">
            <div class="summary-label">Low Stock Alerts</div>
            <div class="summary-value" style="color: #b91c1c;">{{ $lowStockCount }} Items</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Product Description</th>
                <th>Category</th>
                <th class="text-right">Stock</th>
                <th class="text-right">Selling Price</th>
                <th class="text-right">Total Value</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($products as $p)
                @php
                    $threshold = $p->min_stock_threshold ?? 10;
                    $isLow = $p->quantity <= $threshold;
                    $isOut = $p->quantity <= 0;
                @endphp
                <tr>
                    <td>
                        <strong>{{ $p->name }}</strong>
                        @if($p->variations->count() > 0)
                            <span class="variation-text">
                                Variations: {{ $p->variations->pluck('name')->join(', ') }}
                            </span>
                        @endif
                    </td>
                    <td>{{ $p->category->name ?? 'N/A' }}</td>
                    <td class="text-right {{ $isLow ? 'amount' : '' }}" style="{{ $isLow ? 'color: #b91c1c;' : '' }}">
                        {{ number_format($p->quantity, 1) }}
                    </td>
                    <td class="text-right amount">{{ number_format($p->unit_price, 2) }}</td>
                    <td class="text-right amount">{{ number_format($p->quantity * ($p->unit_price ?? 0), 2) }}</td>
                    <td>
                        @if($isOut)
                            <span class="badge badge-danger">Out of Stock</span>
                        @elseif($isLow)
                            <span class="badge badge-warning">Low Stock</span>
                        @else
                            <span class="badge badge-success">Healthy</span>
                        @endif
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

</body>

</html>