<?php

return [
    'basic' => [
        'products' => 5,
        'sales_per_month' => 1000,
        'returns_per_month' => 300,
        'customers' => 500,
        'reports' => 'basic',
        'predictive_insight' => false,
        'tokens' => 'basic',
        'referral' => 'basic',
        'sms' => 300,
        'affiliate_marketing' => false,
        'excel_import_rows' => 1000,
        'custom_api' => false,
        'shopify_woo' => false,
        'users' => 3,
        'data_retention_months' => 12,
        'support_level' => 'standard',
        'audit_logs' => false,
        'support_tickets_per_month' => 3,
    ],

    'pro' => [
        'products' => 10,
        'sales_per_month' => 20000,
        'returns_per_month' => 5000,
        'customers' => 10000,
        'reports' => 'advanced',
        'predictive_insight' => true,
        'tokens' => 'enhanced',
        'referral' => 'tiered',
        'sms' => 3000,
        'affiliate_marketing' => true,
        'excel_import_rows' => 10000,
        'custom_api' => 1,
        'shopify_woo' => 1,
        'users' => 10,
        'data_retention_months' => 36,
        'support_level' => 'priority',
        'audit_logs' => true,
        'support_tickets_per_month' => 30,
    ],

    'custom' => [
        'products' => null,
        'sales_per_month' => null,
        'returns_per_month' => null,
        'customers' => null,
        'reports' => 'custom',
        'predictive_insight' => true,
        'tokens' => 'custom',
        'referral' => 'custom',
        'sms' => null,
        'affiliate_marketing' => true,
        'excel_import_rows' => null,
        'custom_api' => null,
        'shopify_woo' => null,
        'users' => null,
        'data_retention_months' => null,
        'support_level' => 'vip',
        'audit_logs' => true,
        'support_tickets_per_month' => null,
    ],
];

